# Generated by Django 4.1.1 on 2022-09-29 15:22

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_portfolio', '0002_alter_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='home_address',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(0.0, 0.0), srid=4326),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.TextField(default=''),
        ),
    ]
