# Generated by Django 4.1.1 on 2022-10-02 14:56

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.collections
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_portfolio', '0004_loggedinusers'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLocationsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_locations', django.contrib.gis.db.models.fields.MultiPointField(default=django.contrib.gis.geos.collections.MultiPoint(), srid=4326)),
            ],
        ),
    ]
