# Generated by Django 4.1.1 on 2022-10-02 17:27

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.collections
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_portfolio', '0008_alter_userlocationsmodel_user_locations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlocationsmodel',
            name='user_locations',
            field=django.contrib.gis.db.models.fields.MultiPointField(default=django.contrib.gis.geos.collections.MultiPoint(), srid=4326),
        ),
    ]
