# Generated by Django 4.1.1 on 2022-10-03 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_portfolio', '0009_alter_userlocationsmodel_user_locations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
    ]
